'use client'

import { useState } from 'react'
import Link from 'next/link'
import { FileCode, ArrowLeft, Copy, Check, Plus, Trash2 } from 'lucide-react'

interface Redirect {
  id: number
  from: string
  to: string
  type: '301' | '302'
}

export default function HtaccessRedirectPage() {
  const [redirects, setRedirects] = useState<Redirect[]>([
    { id: 1, from: '/old-page', to: '/new-page', type: '301' }
  ])
  const [forceHttps, setForceHttps] = useState(false)
  const [forceWww, setForceWww] = useState<'none' | 'www' | 'non-www'>('none')
  const [customRules, setCustomRules] = useState('')
  const [copied, setCopied] = useState(false)

  const addRedirect = () => {
    setRedirects(prev => [...prev, { id: Date.now(), from: '', to: '', type: '301' }])
  }

  const removeRedirect = (id: number) => {
    setRedirects(prev => prev.filter(r => r.id !== id))
  }

  const updateRedirect = (id: number, field: keyof Redirect, value: string) => {
    setRedirects(prev => prev.map(r => r.id === id ? { ...r, [field]: value } : r))
  }

  const generateCode = (): string => {
    const lines: string[] = ['# Generated by Mumtaz AI Tools', '']

    if (forceHttps || forceWww !== 'none' || redirects.length > 0) {
      lines.push('RewriteEngine On')
      lines.push('')
    }

    if (forceHttps) {
      lines.push('# Force HTTPS')
      lines.push('RewriteCond %{HTTPS} off')
      lines.push('RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]')
      lines.push('')
    }

    if (forceWww === 'www') {
      lines.push('# Force www')
      lines.push('RewriteCond %{HTTP_HOST} !^www\\. [NC]')
      lines.push('RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]')
      lines.push('')
    } else if (forceWww === 'non-www') {
      lines.push('# Force non-www')
      lines.push('RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]')
      lines.push('RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]')
      lines.push('')
    }

    if (redirects.length > 0) {
      lines.push('# Redirects')
      redirects.forEach(r => {
        if (r.from && r.to) {
          lines.push(`Redirect ${r.type} ${r.from} ${r.to}`)
        }
      })
      lines.push('')
    }

    if (customRules.trim()) {
      lines.push('# Custom Rules')
      lines.push(customRules.trim())
      lines.push('')
    }

    return lines.join('\n')
  }

  const code = generateCode()

  const copy = async () => {
    await navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 1200)
  }

  const download = () => {
    const blob = new Blob([code], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = '.htaccess'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen themed-section-bg">
      <div className="relative py-14 md:py-20 overflow-hidden rounded-b-[2rem] themed-section-bg">
        <div className="absolute -top-20 -left-10 w-[200px] h-[600px] rotate-[25deg] rounded-[100px] bg-gradient-to-b from-white/60 via-purple-300/30 to-transparent backdrop-blur-sm border border-white/40" />
        <div className="absolute -top-32 right-[10%] w-[180px] h-[700px] rotate-[-20deg] rounded-[100px] bg-gradient-to-b from-transparent via-violet-400/25 to-white/50 backdrop-blur-sm border border-white/30" />
        <div className="absolute -bottom-40 left-[30%] w-[160px] h-[500px] rotate-[35deg] rounded-[100px] bg-gradient-to-t from-white/50 via-fuchsia-300/20 to-transparent backdrop-blur-sm border border-white/30" />
        <div className="absolute -bottom-20 -right-10 w-[220px] h-[550px] rotate-[-30deg] rounded-[100px] bg-gradient-to-t from-transparent via-indigo-300/25 to-white/60 backdrop-blur-sm border border-white/40" />
        <div className="absolute top-[10%] left-[45%] w-[120px] h-[400px] rotate-[15deg] rounded-[80px] bg-gradient-to-b from-white/40 via-purple-200/20 to-white/30 backdrop-blur-sm border border-white/25" />
        <div className="absolute inset-0 bg-gradient-to-br from-white/40 via-transparent to-white/20 pointer-events-none" />
        <div className="container-custom relative z-10">
          <Link href="/tools" className="inline-flex items-center gap-2 text-purple-600 hover:text-purple-500 mb-8 transition-colors">
            <ArrowLeft className="w-4 h-4" />Back to Tools
          </Link>
          <div className="max-w-3xl mx-auto bg-white/30 backdrop-blur-2xl border border-white/50 rounded-3xl p-8 md:p-12 shadow-[0_8px_40px_rgba(139,92,246,0.12),inset_0_1px_0_rgba(255,255,255,0.6)]">
          <div className="text-center">
            <div className="flex items-center justify-center mb-6">
              <div className="w-16 h-16 rounded-2xl bg-white/30 backdrop-blur-sm border border-white/50 flex items-center justify-center shadow-lg">
                <FileCode className="w-10 h-10 text-white" />
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 font-black bg-gradient-to-r from-slate-800 via-purple-800 to-indigo-700 bg-clip-text text-transparent">.htaccess <span className="text-slate-500">Redirect Generator</span></h1>
            <p className="text-xl text-slate-500 max-w-2xl mx-auto">Generate Apache .htaccess redirect rules easily</p>
          </div>
          </div>
        </div>
      </div>

      <main className="container-custom py-8">
        <div className="max-w-4xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            {/* Options */}
            <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6 space-y-3">
              <h3 className="text-lg font-semibold text-gray-900">Options</h3>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={forceHttps} onChange={(e) => setForceHttps(e.target.checked)} className="rounded text-blue-600" />
                <span className="text-sm text-gray-700">Force HTTPS</span>
              </label>
              <div>
                <label className="block text-xs text-gray-500 mb-1">WWW Preference</label>
                <select value={forceWww} onChange={(e) => setForceWww(e.target.value as any)} className="w-full bg-white border border-gray-300 rounded-lg px-3 py-2 text-gray-900 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                  <option value="none">No preference</option>
                  <option value="www">Force www</option>
                  <option value="non-www">Force non-www</option>
                </select>
              </div>
            </div>

            {/* Redirects */}
            <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6 space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">URL Redirects</h3>
                <button onClick={addRedirect} className="text-sm text-blue-600 hover:text-blue-700 flex items-center gap-1"><Plus className="w-4 h-4" />Add</button>
              </div>
              {redirects.map(r => (
                <div key={r.id} className="flex gap-2 items-start">
                  <select value={r.type} onChange={(e) => updateRedirect(r.id, 'type', e.target.value)} className="bg-white border border-gray-300 rounded-lg px-2 py-1.5 text-sm text-gray-900 w-16">
                    <option value="301">301</option>
                    <option value="302">302</option>
                  </select>
                  <input type="text" value={r.from} onChange={(e) => updateRedirect(r.id, 'from', e.target.value)} placeholder="/old-path" className="flex-1 bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-sm font-mono text-gray-900 focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                  <span className="text-gray-400 py-1.5">→</span>
                  <input type="text" value={r.to} onChange={(e) => updateRedirect(r.id, 'to', e.target.value)} placeholder="/new-path" className="flex-1 bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-sm font-mono text-gray-900 focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                  <button onClick={() => removeRedirect(r.id)} className="text-red-400 hover:text-red-600 py-1.5"><Trash2 className="w-4 h-4" /></button>
                </div>
              ))}
            </div>

            {/* Custom */}
            <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6">
              <h3 className="text-sm font-semibold text-gray-700 mb-2">Custom Rules (optional)</h3>
              <textarea value={customRules} onChange={(e) => setCustomRules(e.target.value)} rows={3} placeholder="Add custom .htaccess rules..." className="w-full bg-white border border-gray-300 rounded-lg px-3 py-2 text-sm text-gray-900 font-mono focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none" />
            </div>
          </div>

          {/* Output */}
          <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6 h-fit sticky top-6">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-gray-700">.htaccess</h3>
              <div className="flex gap-2">
                <button onClick={copy} className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors flex items-center gap-1.5 text-sm">
                  {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}{copied ? 'Copied!' : 'Copy'}
                </button>
                <button onClick={download} className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm">Download</button>
              </div>
            </div>
            <pre className="bg-gray-50 rounded-lg p-4 border border-gray-200 text-sm text-gray-800 whitespace-pre-wrap font-mono">{code}</pre>
          </div>
        </div>
      </main>
    </div>
  )
}
