'use client'

import { useState } from 'react'
import Link from 'next/link'
import { FileCode, ArrowLeft, Copy, Check, Plus, Trash2 } from 'lucide-react'

interface Redirect {
  id: number
  from: string
  to: string
  type: '301' | '302'
}

export default function HtaccessRedirectPage() {
  const [redirects, setRedirects] = useState<Redirect[]>([
    { id: 1, from: '/old-page', to: '/new-page', type: '301' }
  ])
  const [forceHttps, setForceHttps] = useState(false)
  const [forceWww, setForceWww] = useState<'none' | 'www' | 'non-www'>('none')
  const [customRules, setCustomRules] = useState('')
  const [copied, setCopied] = useState(false)

  const addRedirect = () => {
    setRedirects(prev => [...prev, { id: Date.now(), from: '', to: '', type: '301' }])
  }

  const removeRedirect = (id: number) => {
    setRedirects(prev => prev.filter(r => r.id !== id))
  }

  const updateRedirect = (id: number, field: keyof Redirect, value: string) => {
    setRedirects(prev => prev.map(r => r.id === id ? { ...r, [field]: value } : r))
  }

  const generateCode = (): string => {
    const lines: string[] = ['# Generated by One Last AI Tools', '']

    if (forceHttps || forceWww !== 'none' || redirects.length > 0) {
      lines.push('RewriteEngine On')
      lines.push('')
    }

    if (forceHttps) {
      lines.push('# Force HTTPS')
      lines.push('RewriteCond %{HTTPS} off')
      lines.push('RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]')
      lines.push('')
    }

    if (forceWww === 'www') {
      lines.push('# Force www')
      lines.push('RewriteCond %{HTTP_HOST} !^www\\. [NC]')
      lines.push('RewriteRule ^(.*)$ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]')
      lines.push('')
    } else if (forceWww === 'non-www') {
      lines.push('# Force non-www')
      lines.push('RewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]')
      lines.push('RewriteRule ^(.*)$ https://%1%{REQUEST_URI} [L,R=301]')
      lines.push('')
    }

    if (redirects.length > 0) {
      lines.push('# Redirects')
      redirects.forEach(r => {
        if (r.from && r.to) {
          lines.push(`Redirect ${r.type} ${r.from} ${r.to}`)
        }
      })
      lines.push('')
    }

    if (customRules.trim()) {
      lines.push('# Custom Rules')
      lines.push(customRules.trim())
      lines.push('')
    }

    return lines.join('\n')
  }

  const code = generateCode()

  const copy = async () => {
    await navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 1200)
  }

  const download = () => {
    const blob = new Blob([code], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = '.htaccess'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="bg-gradient-to-r from-brand-600 to-accent-600 py-12">
        <div className="container-custom">
          <Link href="/tools" className="inline-flex items-center gap-2 text-blue-100 hover:text-white mb-8 transition-colors">
            <ArrowLeft className="w-4 h-4" />Back to Tools
          </Link>
          <div className="text-center">
            <div className="flex items-center justify-center mb-6">
              <div className="w-20 h-20 bg-white/20 backdrop-blur-sm rounded-2xl flex items-center justify-center shadow-lg">
                <FileCode className="w-10 h-10 text-white" />
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 text-white">.htaccess <span className="text-blue-100">Redirect Generator</span></h1>
            <p className="text-xl text-blue-100 max-w-2xl mx-auto">Generate Apache .htaccess redirect rules easily</p>
          </div>
        </div>
      </div>

      <main className="container-custom py-8">
        <div className="max-w-4xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-4">
            {/* Options */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-lg p-6 space-y-3">
              <h3 className="text-lg font-semibold text-gray-900">Options</h3>
              <label className="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" checked={forceHttps} onChange={(e) => setForceHttps(e.target.checked)} className="rounded text-blue-600" />
                <span className="text-sm text-gray-700">Force HTTPS</span>
              </label>
              <div>
                <label className="block text-xs text-gray-500 mb-1">WWW Preference</label>
                <select value={forceWww} onChange={(e) => setForceWww(e.target.value as any)} className="w-full bg-white border border-gray-300 rounded-lg px-3 py-2 text-gray-900 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent">
                  <option value="none">No preference</option>
                  <option value="www">Force www</option>
                  <option value="non-www">Force non-www</option>
                </select>
              </div>
            </div>

            {/* Redirects */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-lg p-6 space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-gray-900">URL Redirects</h3>
                <button onClick={addRedirect} className="text-sm text-brand-600 hover:text-brand-700 flex items-center gap-1"><Plus className="w-4 h-4" />Add</button>
              </div>
              {redirects.map(r => (
                <div key={r.id} className="flex gap-2 items-start">
                  <select value={r.type} onChange={(e) => updateRedirect(r.id, 'type', e.target.value)} className="bg-white border border-gray-300 rounded-lg px-2 py-1.5 text-sm text-gray-900 w-16">
                    <option value="301">301</option>
                    <option value="302">302</option>
                  </select>
                  <input type="text" value={r.from} onChange={(e) => updateRedirect(r.id, 'from', e.target.value)} placeholder="/old-path" className="flex-1 bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-sm font-mono text-gray-900 focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                  <span className="text-gray-400 py-1.5">→</span>
                  <input type="text" value={r.to} onChange={(e) => updateRedirect(r.id, 'to', e.target.value)} placeholder="/new-path" className="flex-1 bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-sm font-mono text-gray-900 focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                  <button onClick={() => removeRedirect(r.id)} className="text-red-400 hover:text-red-600 py-1.5"><Trash2 className="w-4 h-4" /></button>
                </div>
              ))}
            </div>

            {/* Custom */}
            <div className="bg-white rounded-2xl border border-gray-200 shadow-lg p-6">
              <h3 className="text-sm font-semibold text-gray-700 mb-2">Custom Rules (optional)</h3>
              <textarea value={customRules} onChange={(e) => setCustomRules(e.target.value)} rows={3} placeholder="Add custom .htaccess rules..." className="w-full bg-white border border-gray-300 rounded-lg px-3 py-2 text-sm text-gray-900 font-mono focus:ring-2 focus:ring-blue-500 focus:border-transparent resize-none" />
            </div>
          </div>

          {/* Output */}
          <div className="bg-white rounded-2xl border border-gray-200 shadow-lg p-6 h-fit sticky top-6">
            <div className="flex items-center justify-between mb-3">
              <h3 className="text-sm font-semibold text-gray-700">.htaccess</h3>
              <div className="flex gap-2">
                <button onClick={copy} className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors flex items-center gap-1.5 text-sm">
                  {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}{copied ? 'Copied!' : 'Copy'}
                </button>
                <button onClick={download} className="px-3 py-1.5 bg-brand-600 hover:bg-brand-700 text-white rounded-lg transition-colors text-sm">Download</button>
              </div>
            </div>
            <pre className="bg-gray-50 rounded-lg p-4 border border-gray-200 text-sm text-gray-800 whitespace-pre-wrap font-mono">{code}</pre>
          </div>
        </div>
      </main>
    </div>
  )
}
