'use client'

import { useState } from 'react'
import Link from 'next/link'
import { Bot, ArrowLeft, Copy, Check, Plus, Trash2, Info, ChevronDown, ChevronUp } from 'lucide-react'

interface RobotsConfig {
  userAgent: string
  allows: string[]
  disallows: string[]
  crawlDelay: string
  sitemap: string
}

const PRESETS = [
  { label: 'Allow All', configs: [{ userAgent: '*', allows: ['/'], disallows: [], crawlDelay: '', sitemap: '' }] },
  { label: 'Block All', configs: [{ userAgent: '*', allows: [], disallows: ['/'], crawlDelay: '', sitemap: '' }] },
  { label: 'Standard SEO', configs: [{ userAgent: '*', allows: ['/'], disallows: ['/admin/', '/private/', '/api/', '/tmp/', '/*.json$'], crawlDelay: '', sitemap: 'https://example.com/sitemap.xml' }] },
  { label: 'Block AI Bots', configs: [
    { userAgent: 'GPTBot', allows: [], disallows: ['/'], crawlDelay: '', sitemap: '' },
    { userAgent: 'ChatGPT-User', allows: [], disallows: ['/'], crawlDelay: '', sitemap: '' },
    { userAgent: 'Google-Extended', allows: [], disallows: ['/'], crawlDelay: '', sitemap: '' },
    { userAgent: 'CCBot', allows: [], disallows: ['/'], crawlDelay: '', sitemap: '' },
  ]},
  { label: 'WordPress', configs: [{ userAgent: '*', allows: ['/'], disallows: ['/wp-admin/', '/wp-includes/', '/wp-content/plugins/', '/trackback/', '/feed/', '/comments/'], crawlDelay: '10', sitemap: 'https://example.com/sitemap.xml' }] },
]

const COMMON_BOTS = ['*', 'Googlebot', 'Bingbot', 'Slurp', 'DuckDuckBot', 'Baiduspider', 'YandexBot', 'facebot', 'ia_archiver', 'GPTBot', 'ChatGPT-User', 'Google-Extended', 'CCBot', 'Applebot', 'Twitterbot']

export default function RobotsTxtGeneratorPage() {
  const [configs, setConfigs] = useState<RobotsConfig[]>([
    { userAgent: '*', allows: ['/'], disallows: ['/admin/', '/private/'], crawlDelay: '', sitemap: 'https://example.com/sitemap.xml' }
  ])
  const [copied, setCopied] = useState(false)
  const [testUrl, setTestUrl] = useState('')
  const [testResult, setTestResult] = useState<{ allowed: boolean; rule: string } | null>(null)
  const [showInfo, setShowInfo] = useState(false)

  const applyPreset = (preset: typeof PRESETS[0]) => setConfigs(preset.configs)

  const addConfig = () => {
    setConfigs(prev => [...prev, { userAgent: 'Googlebot', allows: ['/'], disallows: [], crawlDelay: '', sitemap: '' }])
  }

  const removeConfig = (idx: number) => setConfigs(prev => prev.filter((_, i) => i !== idx))

  const updateConfig = (idx: number, field: keyof RobotsConfig, value: string | string[]) => {
    setConfigs(prev => prev.map((c, i) => i === idx ? { ...c, [field]: value } : c))
  }

  const addPath = (idx: number, type: 'allows' | 'disallows') => {
    setConfigs(prev => prev.map((c, i) => i === idx ? { ...c, [type]: [...c[type], '/'] } : c))
  }

  const removePath = (idx: number, type: 'allows' | 'disallows', pathIdx: number) => {
    setConfigs(prev => prev.map((c, i) => i === idx ? { ...c, [type]: c[type].filter((_, j) => j !== pathIdx) } : c))
  }

  const updatePath = (idx: number, type: 'allows' | 'disallows', pathIdx: number, value: string) => {
    setConfigs(prev => prev.map((c, i) => i === idx ? { ...c, [type]: c[type].map((p, j) => j === pathIdx ? value : p) } : c))
  }

  const testUrlAccess = () => {
    if (!testUrl) return
    const path = testUrl.startsWith('/') ? testUrl : '/' + testUrl
    for (const config of configs) {
      if (config.userAgent !== '*') continue
      for (const d of config.disallows) {
        if (d && path.startsWith(d.replace('*', ''))) {
          for (const a of config.allows) {
            if (a && path.startsWith(a) && a.length > d.length) {
              setTestResult({ allowed: true, rule: `Allow: ${a}` })
              return
            }
          }
          setTestResult({ allowed: false, rule: `Disallow: ${d}` })
          return
        }
      }
    }
    setTestResult({ allowed: true, rule: 'No matching Disallow rule' })
  }

  const generateCode = (): string => {
    const lines: string[] = ['# robots.txt generated by Mumtaz AI Tools', '']
    configs.forEach((config, idx) => {
      if (idx > 0) lines.push('')
      lines.push(`User-agent: ${config.userAgent}`)
      config.allows.forEach(p => lines.push(`Allow: ${p}`))
      config.disallows.forEach(p => lines.push(`Disallow: ${p}`))
      if (config.crawlDelay) lines.push(`Crawl-delay: ${config.crawlDelay}`)
    })
    const sitemaps = configs.map(c => c.sitemap).filter(Boolean)
    if (sitemaps.length > 0) {
      lines.push('')
      ;[...new Set(sitemaps)].forEach(s => lines.push(`Sitemap: ${s}`))
    }
    return lines.join('\n')
  }

  const code = generateCode()

  const copy = async () => {
    await navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 1200)
  }

  const download = () => {
    const blob = new Blob([code], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url; a.download = 'robots.txt'; a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen themed-section-bg">
      <div className="relative py-14 md:py-20 overflow-hidden rounded-b-[2rem] themed-section-bg">
        <div className="absolute -top-20 -left-10 w-[200px] h-[600px] rotate-[25deg] rounded-[100px] bg-gradient-to-b from-white/60 via-purple-300/30 to-transparent backdrop-blur-sm border border-white/40" />
        <div className="absolute -top-32 right-[10%] w-[180px] h-[700px] rotate-[-20deg] rounded-[100px] bg-gradient-to-b from-transparent via-violet-400/25 to-white/50 backdrop-blur-sm border border-white/30" />
        <div className="absolute -bottom-40 left-[30%] w-[160px] h-[500px] rotate-[35deg] rounded-[100px] bg-gradient-to-t from-white/50 via-fuchsia-300/20 to-transparent backdrop-blur-sm border border-white/30" />
        <div className="absolute -bottom-20 -right-10 w-[220px] h-[550px] rotate-[-30deg] rounded-[100px] bg-gradient-to-t from-transparent via-indigo-300/25 to-white/60 backdrop-blur-sm border border-white/40" />
        <div className="absolute top-[10%] left-[45%] w-[120px] h-[400px] rotate-[15deg] rounded-[80px] bg-gradient-to-b from-white/40 via-purple-200/20 to-white/30 backdrop-blur-sm border border-white/25" />
        <div className="absolute inset-0 bg-gradient-to-br from-white/40 via-transparent to-white/20 pointer-events-none" />
        <div className="container-custom relative z-10">
          <Link href="/tools" className="inline-flex items-center gap-2 text-purple-600 hover:text-purple-500 mb-8 transition-colors">
            <ArrowLeft className="w-4 h-4" />Back to Tools
          </Link>
          <div className="max-w-3xl mx-auto bg-white/30 backdrop-blur-2xl border border-white/50 rounded-3xl p-8 md:p-12 shadow-[0_8px_40px_rgba(139,92,246,0.12),inset_0_1px_0_rgba(255,255,255,0.6)]">
          <div className="text-center">
            <div className="flex items-center justify-center mb-6">
              <div className="w-16 h-16 rounded-2xl bg-white/30 backdrop-blur-sm border border-white/50 flex items-center justify-center shadow-lg">
                <Bot className="w-10 h-10 text-white" />
              </div>
            </div>
            <h1 className="text-4xl md:text-5xl font-bold mb-4 font-black bg-gradient-to-r from-slate-800 via-purple-800 to-indigo-700 bg-clip-text text-transparent">Robots.txt <span className="text-slate-500">Generator</span></h1>
            <p className="text-xl text-slate-500 max-w-2xl mx-auto">Generate a robots.txt file with presets and URL testing</p>
          </div>
          </div>
        </div>
      </div>

      <main className="container-custom py-8">
        <div className="max-w-5xl mx-auto">
          {/* Presets */}
          <div className="mb-4 flex flex-wrap gap-2">
            <span className="text-xs font-semibold text-gray-500 uppercase self-center mr-1">Presets:</span>
            {PRESETS.map(p => (
              <button key={p.label} onClick={() => applyPreset(p)} className="px-3 py-1.5 bg-white hover:bg-gray-50 border border-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors shadow-sm">{p.label}</button>
            ))}
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Form */}
            <div className="space-y-4">
              {configs.map((config, idx) => (
                <div key={idx} className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6 space-y-3">
                  <div className="flex items-center justify-between">
                    <h3 className="text-sm font-semibold text-gray-700">Rule #{idx + 1}</h3>
                    {configs.length > 1 && <button onClick={() => removeConfig(idx)} className="text-red-400 hover:text-red-600"><Trash2 className="w-4 h-4" /></button>}
                  </div>
                  <div>
                    <label className="block text-xs text-gray-500 mb-1">User-Agent</label>
                    <select value={COMMON_BOTS.includes(config.userAgent) ? config.userAgent : '__custom'} onChange={(e) => { if (e.target.value !== '__custom') updateConfig(idx, 'userAgent', e.target.value) }} className="w-full bg-white border border-gray-300 rounded-lg px-3 py-2 text-gray-900 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent mb-1">
                      {COMMON_BOTS.map(b => <option key={b} value={b}>{b}</option>)}
                      {!COMMON_BOTS.includes(config.userAgent) && <option value="__custom">{config.userAgent} (custom)</option>}
                    </select>
                    <input type="text" value={config.userAgent} onChange={(e) => updateConfig(idx, 'userAgent', e.target.value)} placeholder="Custom user-agent" className="w-full bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-gray-900 text-sm font-mono focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                  </div>
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="text-xs text-green-600 font-semibold">Allow</label>
                      <button onClick={() => addPath(idx, 'allows')} className="text-xs text-blue-600 hover:text-blue-700">+ Add</button>
                    </div>
                    {config.allows.map((p, pi) => (
                      <div key={pi} className="flex gap-2 mb-1">
                        <input type="text" value={p} onChange={(e) => updatePath(idx, 'allows', pi, e.target.value)} className="flex-1 bg-green-50 border border-green-200 rounded-lg px-3 py-1.5 text-gray-900 text-sm font-mono focus:ring-2 focus:ring-green-400 focus:border-transparent" />
                        <button onClick={() => removePath(idx, 'allows', pi)} className="text-red-400 hover:text-red-600"><Trash2 className="w-3.5 h-3.5" /></button>
                      </div>
                    ))}
                  </div>
                  <div>
                    <div className="flex items-center justify-between mb-1">
                      <label className="text-xs text-red-600 font-semibold">Disallow</label>
                      <button onClick={() => addPath(idx, 'disallows')} className="text-xs text-blue-600 hover:text-blue-700">+ Add</button>
                    </div>
                    {config.disallows.map((p, pi) => (
                      <div key={pi} className="flex gap-2 mb-1">
                        <input type="text" value={p} onChange={(e) => updatePath(idx, 'disallows', pi, e.target.value)} className="flex-1 bg-red-50 border border-red-200 rounded-lg px-3 py-1.5 text-gray-900 text-sm font-mono focus:ring-2 focus:ring-red-400 focus:border-transparent" />
                        <button onClick={() => removePath(idx, 'disallows', pi)} className="text-red-400 hover:text-red-600"><Trash2 className="w-3.5 h-3.5" /></button>
                      </div>
                    ))}
                  </div>
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-xs text-gray-500 mb-1">Crawl Delay (sec)</label>
                      <input type="number" min={0} value={config.crawlDelay} onChange={(e) => updateConfig(idx, 'crawlDelay', e.target.value)} placeholder="10" className="w-full bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-gray-900 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                    </div>
                    <div>
                      <label className="block text-xs text-gray-500 mb-1">Sitemap URL</label>
                      <input type="text" value={config.sitemap} onChange={(e) => updateConfig(idx, 'sitemap', e.target.value)} placeholder="https://..." className="w-full bg-white border border-gray-300 rounded-lg px-3 py-1.5 text-gray-900 text-sm focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                    </div>
                  </div>
                </div>
              ))}
              <button onClick={addConfig} className="w-full px-4 py-3 border-2 border-dashed border-gray-300 rounded-2xl text-gray-500 hover:border-blue-400 hover:text-blue-600 transition-colors flex items-center justify-center gap-2">
                <Plus className="w-4 h-4" />Add User-Agent Rule
              </button>
            </div>

            {/* Output */}
            <div className="space-y-4">
              {/* Test URL */}
              <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">Test URL Access</h3>
                <div className="flex gap-2">
                  <input type="text" value={testUrl} onChange={e => setTestUrl(e.target.value)} onKeyDown={e => e.key === 'Enter' && testUrlAccess()} placeholder="/admin/dashboard" className="flex-1 bg-white border border-gray-300 rounded-lg px-3 py-2 text-gray-900 text-sm font-mono focus:ring-2 focus:ring-blue-500 focus:border-transparent" />
                  <button onClick={testUrlAccess} className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-sm font-semibold transition-colors">Test</button>
                </div>
                {testResult && (
                  <div className={`mt-2 px-3 py-2 rounded-lg text-sm ${testResult.allowed ? 'bg-green-50 text-green-700 border border-green-200' : 'bg-red-50 text-red-700 border border-red-200'}`}>
                    {testResult.allowed ? 'ALLOWED' : 'BLOCKED'} — {testResult.rule}
                  </div>
                )}
              </div>

              {/* Code */}
              <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg p-6 sticky top-6">
                <div className="flex items-center justify-between mb-3">
                  <h3 className="text-sm font-semibold text-gray-700">robots.txt</h3>
                  <div className="flex gap-2">
                    <button onClick={copy} className="px-3 py-1.5 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors flex items-center gap-1.5 text-sm">
                      {copied ? <Check className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}{copied ? 'Copied!' : 'Copy'}
                    </button>
                    <button onClick={download} className="px-3 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors text-sm">Download</button>
                  </div>
                </div>
                <pre className="bg-gray-50 rounded-lg p-4 border border-gray-200 text-sm text-gray-800 whitespace-pre-wrap font-mono">{code}</pre>
              </div>

              {/* Info */}
              <div className="bg-white/40 backdrop-blur-lg rounded-2xl border border-white/60 shadow-lg">
                <button onClick={() => setShowInfo(!showInfo)} className="w-full flex items-center justify-between p-6">
                  <h3 className="text-sm font-semibold text-gray-700 flex items-center gap-2"><Info className="w-4 h-4" />About robots.txt</h3>
                  {showInfo ? <ChevronUp className="w-4 h-4 text-gray-400" /> : <ChevronDown className="w-4 h-4 text-gray-400" />}
                </button>
                {showInfo && (
                  <div className="px-6 pb-6 grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {[
                      { title: 'How It Works', desc: 'robots.txt is placed at your site root. Crawlers check it before accessing pages. It\'s advisory — well-behaved bots obey it.' },
                      { title: 'Allow vs Disallow', desc: 'Allow paths override matching Disallow paths of the same length. More specific rules take priority.' },
                      { title: 'AI Bot Blocking', desc: 'GPTBot, Google-Extended, CCBot can be blocked to prevent AI training on your content.' },
                      { title: 'Crawl-delay', desc: 'Tells bots to wait N seconds between requests. Not all bots respect this (Google ignores it).' },
                    ].map(c => (
                      <div key={c.title} className="bg-gray-50 rounded-lg p-3 border border-gray-200">
                        <div className="font-semibold text-gray-900 text-sm">{c.title}</div>
                        <div className="text-xs text-gray-600 mt-1">{c.desc}</div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
